package:
  name: pypot
  # version automatically set in the build.sh and blt.bat

source:
  path: ../


build:
  # Fix conda issue with location of vrep shared libraries path
  binary_relocation: False
  entry_points:
    - dxl-config = pypot.tools.dxlconfig:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy
    - pyserial >2.6
    - scipy
    - enum34  [py27 or py33]
    - pyzmq
    - tornado
    - bottle
    - ikpy
    - poppy-creature >=2

  run:
    - python
    - numpy
    - pyserial >2.6
    - scipy
    - enum34  [py27 or py33]
    - pyzmq
    - tornado
    - bottle
    - ikpy

test:
  # TODO upload these requires to conda to make tests
  # requires:
  #   - poppy-creature
  #   - requests
  #   - poppy-ergo-jr

  # Python imports
  imports:
    - pypot
    - pypot.dynamixel
    - pypot.dynamixel.io
    - pypot.dynamixel.protocol
    - pypot.primitive
    - pypot.robot
    - pypot.sensor
    - pypot.sensor.camera
    - pypot.sensor.imagefeature
    - pypot.sensor.kinect
    - pypot.server
    - pypot.tools
    - pypot.utils
    - pypot.vrep [not armv7l]
    - pypot.vrep.remoteApiBindings [not armv7l]

  commands:
    - dxl-config --help
about:
  home: https://github.com/poppy-project/pypot
  summary: 'Python Library for Robot Control'
  license_file: LICENSE.txt
  license: GNU GENERAL PUBLIC LICENSE Version 3
